/**
 * Modulo API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: simonokello93@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.Expense
import io.swagger.client.model.InlineResponse200
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object ExpensesApi {

  /**
   * 
   * Expected answers:
   *   code 201 : Expense 
   * 
   * Available security schemes:
   *   Bearer (apiKey)
   * 
   * @param data 
   */
  def expensesCreate(data: Expense)(implicit apiKey: ApiKeyValue): ApiRequest[Expense] =
    ApiRequest[Expense](ApiMethods.POST, "https://moduloapi.herokuapp.com/api", "/expenses/", "application/json")
      .withApiKey(apiKey, "Authorization", HEADER)
      .withBody(data)
      .withSuccessResponse[Expense](201)
        /**
   * 
   * Expected answers:
   *   code 204 :  
   * 
   * Available security schemes:
   *   Bearer (apiKey)
   * 
   * @param id A unique integer value identifying this expense.
   */
  def expensesDelete(id: Int)(implicit apiKey: ApiKeyValue): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.DELETE, "https://moduloapi.herokuapp.com/api", "/expenses/{id}", "application/json")
      .withApiKey(apiKey, "Authorization", HEADER)
      .withPathParam("id", id)
      .withSuccessResponse[Unit](204)
        /**
   * 
   * Expected answers:
   *   code 200 : InlineResponse200 
   * 
   * Available security schemes:
   *   Bearer (apiKey)
   * 
   * @param page A page number within the paginated result set.
   */
  def expensesList(page: Option[Int] = None)(implicit apiKey: ApiKeyValue): ApiRequest[InlineResponse200] =
    ApiRequest[InlineResponse200](ApiMethods.GET, "https://moduloapi.herokuapp.com/api", "/expenses/", "application/json")
      .withApiKey(apiKey, "Authorization", HEADER)
      .withQueryParam("page", page)
      .withSuccessResponse[InlineResponse200](200)
        /**
   * 
   * Expected answers:
   *   code 200 : Expense 
   * 
   * Available security schemes:
   *   Bearer (apiKey)
   * 
   * @param id A unique integer value identifying this expense.
   * @param data 
   */
  def expensesPartialUpdate(id: Int, data: Expense)(implicit apiKey: ApiKeyValue): ApiRequest[Expense] =
    ApiRequest[Expense](ApiMethods.PATCH, "https://moduloapi.herokuapp.com/api", "/expenses/{id}", "application/json")
      .withApiKey(apiKey, "Authorization", HEADER)
      .withBody(data)
      .withPathParam("id", id)
      .withSuccessResponse[Expense](200)
        /**
   * 
   * Expected answers:
   *   code 200 : Expense 
   * 
   * Available security schemes:
   *   Bearer (apiKey)
   * 
   * @param id A unique integer value identifying this expense.
   */
  def expensesRead(id: Int)(implicit apiKey: ApiKeyValue): ApiRequest[Expense] =
    ApiRequest[Expense](ApiMethods.GET, "https://moduloapi.herokuapp.com/api", "/expenses/{id}", "application/json")
      .withApiKey(apiKey, "Authorization", HEADER)
      .withPathParam("id", id)
      .withSuccessResponse[Expense](200)
        /**
   * 
   * Expected answers:
   *   code 200 : Expense 
   * 
   * Available security schemes:
   *   Bearer (apiKey)
   * 
   * @param id A unique integer value identifying this expense.
   * @param data 
   */
  def expensesUpdate(id: Int, data: Expense)(implicit apiKey: ApiKeyValue): ApiRequest[Expense] =
    ApiRequest[Expense](ApiMethods.PUT, "https://moduloapi.herokuapp.com/api", "/expenses/{id}", "application/json")
      .withApiKey(apiKey, "Authorization", HEADER)
      .withBody(data)
      .withPathParam("id", id)
      .withSuccessResponse[Expense](200)
      

}

