/**
 * Modulo API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: simonokello93@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.Income
import io.swagger.client.model.InlineResponse2001
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object IncomeApi {

  /**
   * 
   * Expected answers:
   *   code 201 : Income 
   * 
   * Available security schemes:
   *   Bearer (apiKey)
   * 
   * @param data 
   */
  def incomeCreate(data: Income)(implicit apiKey: ApiKeyValue): ApiRequest[Income] =
    ApiRequest[Income](ApiMethods.POST, "https://moduloapi.herokuapp.com/api", "/income/", "application/json")
      .withApiKey(apiKey, "Authorization", HEADER)
      .withBody(data)
      .withSuccessResponse[Income](201)
        /**
   * 
   * Expected answers:
   *   code 204 :  
   * 
   * Available security schemes:
   *   Bearer (apiKey)
   * 
   * @param id A unique integer value identifying this income.
   */
  def incomeDelete(id: Int)(implicit apiKey: ApiKeyValue): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.DELETE, "https://moduloapi.herokuapp.com/api", "/income/{id}", "application/json")
      .withApiKey(apiKey, "Authorization", HEADER)
      .withPathParam("id", id)
      .withSuccessResponse[Unit](204)
        /**
   * 
   * Expected answers:
   *   code 200 : InlineResponse2001 
   * 
   * Available security schemes:
   *   Bearer (apiKey)
   * 
   * @param page A page number within the paginated result set.
   */
  def incomeList(page: Option[Int] = None)(implicit apiKey: ApiKeyValue): ApiRequest[InlineResponse2001] =
    ApiRequest[InlineResponse2001](ApiMethods.GET, "https://moduloapi.herokuapp.com/api", "/income/", "application/json")
      .withApiKey(apiKey, "Authorization", HEADER)
      .withQueryParam("page", page)
      .withSuccessResponse[InlineResponse2001](200)
        /**
   * 
   * Expected answers:
   *   code 200 : Income 
   * 
   * Available security schemes:
   *   Bearer (apiKey)
   * 
   * @param id A unique integer value identifying this income.
   * @param data 
   */
  def incomePartialUpdate(id: Int, data: Income)(implicit apiKey: ApiKeyValue): ApiRequest[Income] =
    ApiRequest[Income](ApiMethods.PATCH, "https://moduloapi.herokuapp.com/api", "/income/{id}", "application/json")
      .withApiKey(apiKey, "Authorization", HEADER)
      .withBody(data)
      .withPathParam("id", id)
      .withSuccessResponse[Income](200)
        /**
   * 
   * Expected answers:
   *   code 200 : Income 
   * 
   * Available security schemes:
   *   Bearer (apiKey)
   * 
   * @param id A unique integer value identifying this income.
   */
  def incomeRead(id: Int)(implicit apiKey: ApiKeyValue): ApiRequest[Income] =
    ApiRequest[Income](ApiMethods.GET, "https://moduloapi.herokuapp.com/api", "/income/{id}", "application/json")
      .withApiKey(apiKey, "Authorization", HEADER)
      .withPathParam("id", id)
      .withSuccessResponse[Income](200)
        /**
   * 
   * Expected answers:
   *   code 200 : Income 
   * 
   * Available security schemes:
   *   Bearer (apiKey)
   * 
   * @param id A unique integer value identifying this income.
   * @param data 
   */
  def incomeUpdate(id: Int, data: Income)(implicit apiKey: ApiKeyValue): ApiRequest[Income] =
    ApiRequest[Income](ApiMethods.PUT, "https://moduloapi.herokuapp.com/api", "/income/{id}", "application/json")
      .withApiKey(apiKey, "Authorization", HEADER)
      .withBody(data)
      .withPathParam("id", id)
      .withSuccessResponse[Income](200)
      

}

