/**
 * Modulo API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: simonokello93@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Income (
  id: Option[Int] = None,
  source: IncomeEnums.Source,
  description: String,
  amount: String,
  date: Date
) extends ApiModel

object IncomeEnums {

  type Source = Source.Value
  object Source extends Enumeration {
    val Salary = Value("Salary")
    val Gift = Value("Gift")
    val Freelance = Value("Freelance")
    val Loan = Value("Loan")
    val Business = Value("Business")
  }

}

